version: "3.9"
services:
  db:
    image: mysql:9.0.1
    container_name: rails_mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      TZ: "${TZ:-Asia/Tokyo}"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3306:3306'
  web:
    build: .
    container_name: rails_web
    volumes:
      - .:/var/www
    environment:
      TZ: "${TZ:-Asia/Tokyo}"
      MYSQL_USERNAME: "${MYSQL_USERNAME:-root}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-root}"
      MYSQL_HOST: "${MYSQL_HOST:-db}"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql-data:
