version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: rails_mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
  web:
    build: .
    container_name: rails_web
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
volumes:
  mysql-data:
    driver: local
